# Generated by Django 5.1.3 on 2024-12-09 01:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='hybird_sear_created_3a860f_idx'), models.Index(fields=['last_activity'], name='hybird_sear_last_ac_00a555_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('query_text', models.TextField()),
                ('query_embedding', models.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hybird_search.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('result_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('search_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hybird_search.searchhistory')),
                ('violation_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_manager.violationevent')),
            ],
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['created_at'], name='hybird_sear_created_fd5e82_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['similarity_score'], name='hybird_sear_similar_c7e54d_idx'),
        ),
        migrations.AddIndex(
            model_name='searchresult',
            index=models.Index(fields=['rank'], name='hybird_sear_rank_3c693d_idx'),
        ),
    ]
